service: ITKGitHubCDashStatus

provider:
  name: azure
  location: East US
  environment:
    GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}

plugins:
  - serverless-azure-functions

functions:
  pullRequestStatusWebhook:
    handler: handler.pullRequestStatusWebhook
    events:
      - http: true
        x-azure-settings:
          webHookType: github
          methods:
            - post
      - http: true
        x-azure-settings:
          direction: out
          name: res
